# Generated by Django 4.1 on 2022-10-06 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apolice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('preco', models.CharField(max_length=45)),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=45)),
                ('placa', models.CharField(max_length=45)),
                ('ano', models.CharField(max_length=45)),
                ('apolice_id', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('sobrenome', models.CharField(max_length=45)),
                ('rg', models.CharField(max_length=45)),
                ('cpf', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente_has_carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carro_id', models.CharField(max_length=45)),
                ('cliente_id', models.ManyToManyField(to='alexandre_seguros.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Accidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhe', models.CharField(max_length=45)),
                ('data', models.DateField()),
                ('carro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alexandre_seguros.carro')),
            ],
        ),
    ]
